apiVersion: apps/v1
kind: Deployment
metadata:
  name: juliet-deployment
  labels: 
    app: juliet
    backstage.io/kubernetes-id: juliet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: juliet
  template:
    metadata:
      labels:
        app: juliet
    spec:
      containers:
      - name: juliet
        image: moali404/nextjs_docker:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
