apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  labels: 
   backstage.io/kubernetes-id: juliet-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: moali404/nextjs_docker:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
